### ISSUE TITLE
Buy-by-text prototype

### ISSUE THREAD

**Issue by stresslimit** [FoxComm/highlander#1076]
Demo customer interaction to purchase via SMS text message. User flow:

1. **Suggest Upsell admin button** 
  Admin finds a customer record and clicks "Suggest Upsell", which POSTs to a new API endpoint. [Ultimately this event could be triggered by a purchase for post-purchase upsell, or a regular interval for a subscription business, abandoned cart timeout, etc etc. But for now a button in the admin will allow us to control the flow of the demo]
1. **Suggest Upsell endpoint** 
  The new endpoint handler then hits our cross-sell service to get a product to suggest [based on last product purchased for now, and filtering out all products already purchased], and triggers an event that an upsell has been suggested to the user. 
1. **Upsell Suggested event listener** 
  Subscribes to the "upsell has been suggested" event, takes the args and sends them to Dexter webhook endpoint to start the customer conversation.
1. **Customer SMS reply handler** 
  Internet-accessible endpoint protected by some simple secret token, which receives user phone# [perhaps user ID], product ID, and POSTs to Fox API to create a cart, add the product in question and auto-checkout with default settings [card & address]. Probably a google cloud function.

### Suggest Upsell admin button
- [ ] Button in admin on customer record to send "suggest upsell" to customer

### Suggest Upsell endpoint
API endpoint to receive "suggest" action
- [ ] Receive POST from admin via ajax
- [ ] ask Xsell service for a product to suggest
- [ ] design "suggest product" name and schema
- [ ] create "suggest product" event

Event must contain at minimum:
```
- 1 product with minimal model:
  - ID
  - name
  - short description
  - 1 imageurl, etc
- user phone#
- probably also user ID for completeness
```

### Upsell Suggested event listener
- [ ] Listens to "suggest upsell" event and POSTs to Dexter

### Customer SMS reply handler
- [ ] Receives "yes" from Dexter webhook and creates the new upsell order via core Fox API
