### ISSUE TITLE
CMS: Updates to Images

### ISSUE THREAD

**Issue by bswineford** [FoxComm/highlander#1223]
Under the Images tab interface, we want to make the following updates in preparation for new CMS features.

**Docs:**
- [Link to mocks on Zeplin](https://zpl.io/ZN3OrL)

**To Dos:**
- [x] Change name of tab from "Images" to "Media" (one day we'll have video, too!)
- [x] Update the button style that allows the user to upload media via browsing the desktop
- [x] Add button that allows the user to upload media via a url. Clicking this opens a modal, with:
     - [x] URL input
- [x] The grid view of uploaded images should auto-crop the image square
- [x] Remove the title and upload timestamp from the grid view of uploaded images
- [x] Simplify drag animation [ease in/out, not bounce]
- [x] Clicking the image should open the new edit modal, with:
     - [x] A larger, uncropped preview of the image
     - [x] Button to delete the image
     - [x] The following fields:
          - [x] Remove editable image title
          - ~~[ ] Add editable slug field~~
          - [x] Make URL field selectable (so user can copy), but not editable
          - ~~[ ] Ability to "Set As", with choices as checkboxes~~
     - [x] Escape key should close the modal
