### ISSUE TITLE
Super Fat Appliance Base Image

### ISSUE THREAD

**Issue by pavel-main** [FoxComm/highlander#1243]
Epic #1112 

Let's look at what can be minimized in [goldrush_appliance.yml](https://github.com/FoxComm/highlander/blob/master/tabernacle/ansible/goldrush_appliance.yml#L43-L70)

### TODO

- [x] Move as much as possible roles to base images. Candidates: 
    - [x] Common (`dev/appliance`, `dev/dashboard`, `dev/consul_agent`)
    - [x] Database setup (`dev/db`, `dev/db_ic`)
    - [x] Nginx setup (`dev/balancer`, `demo/balancer`)
- [x] Remove most parts of `dev/zookeeper`, just ensure that systemd services are started in correct order (check #1138 for more info). Keep in mind that all this services can be smeared across tinystack of 3 instances - use conditionals.
- [x] Merge all `hotfix/*` roles tasks to related base roles
