### ISSUE TITLE
Automated storefront deployments via BuildKite

### ISSUE THREAD

**Issue by pavel-main** [FoxComm/highlander#1245]
Epic #1112 

### Todo

- [x] Rename https://td-prod.foxcommerce.com to https://td-stage.foxcomerce.com
- [x] Launch a Buildkite Agent in `foxcommerce-production-shared` project, configure it to work with `topdrawer` queue
- [x] Deal with Sinopia access mess to properly fetch storefront dependencies (#1301)
- [x] Create a Buildkite pipeline to checkout storefront and build, dockerize and push containers to related registry (#1325)
- [x] Repeat the same steps for TPG staging (#1454)
- [x] Repeat the same steps for Pure Demo (#1407)
- [x] Fix zero-downtime deployments via Marathon API (workaround 111733d0e664093dcad434820e08d100ccb189ce)

### Future

* Setup a webhook for deploying specific branches for Pure via [Buildkite API](https://buildkite.com/docs/rest-api/builds#create-a-build)
* Create an Ansible script to prepare new GitHub release via [Releases API](https://developer.github.com/v3/repos/releases/)
* Update Marathon to a newer version to (try to) have a real zero-downtime deployments

### Links

Buildkite pipelines:
* [Deploy Pure to Demo](https://buildkite.com/foxcommerce/deploy-pure-to-demo)
* [Deploy TopDrawer Storefront Stage](https://buildkite.com/foxcommerce/deploy-topdrawer-storefront-stage)
* [Deploy TPG Storefront Stage](https://buildkite.com/foxcommerce/deploy-tpg-storefront-stage)
