### ISSUE TITLE
Demo store bugs

### ISSUE THREAD

**Issue by stresslimit** [FoxComm/highlander#1378]
Replaces #1200 

### Upsell SMS
- [x] **can't suggest upsell** [screenshot](https://cloud.githubusercontent.com/assets/199718/24974116/231bfa7a-1f8f-11e7-8002-22ab95846423.png) 
Current progress [Issue 1426](https://github.com/FoxComm/highlander/issues/1426)

### Catalog browsing
- [ ] **sort by name doesn't work; should be alphabetical by name**  (@anru and @narma )
- [ ] (taken by @anru) All clickable elements should have `cursor:pointer` including sort order [sorry for conflicting instructions on this one]
- [x] Clicking facets should add URL params & push state. Back button from PDP should take you back to the same state (@glovaeugene)
- [ ] Product card hover state [needs design @mourningking]

### PDP
- [x] hide breadcrumb
- [x] **coming from a catalog page that you've scrolled down, you arrive on PDP already scrolled down. Must start at the top of the page**
- [x] do not allow deselecting variants [color size etc]  (@glovaeugene)
- [ ] nicer alert to choose variants [needs design @mourningking]

### Checkout 
- [x] must use same checkbox component as faceted search. There's no reason it shouldn't be the same ui component (@glovaeugene)
- [x] padding of different page sections is not harmonious: top padding is less, bottom padding is more. Content should look centred in the outlined boxes  (@glovaeugene)
- [x] Modals not centred in safari [screenshot](https://cloud.githubusercontent.com/assets/199718/24975226/f7175772-1f92-11e7-96bb-3072fbd7f133.png) [safari_center_modal_fix](https://cloud.githubusercontent.com/assets/833843/24985033/779748b8-1fa6-11e7-9bad-d940d8a3abf8.png)

- [x] Address & Delivery modals: entire option should be clickable, not just radio & text [screenshot](https://cloud.githubusercontent.com/assets/199718/24975908/5f91b7f0-1f95-11e7-9cc1-32c14902176f.png)
- [x] if user doesn't have a saved address, should jump to address modal in Add New state  (@glovaeugene)
- [x] `esc` key should close modals  (@glovaeugene)

### Forgot password
- [x] Text "No worries..." shouldn't be light (check font-weight). (@glovaeugene)
- [x] Submit button — no caps (@glovaeugene)
- [x] Let's make margin between header and text to 16px (I updated screen on Zeplin) (@glovaeugene)

### Sign up
- [x] Remove show/hide button inside password field. We will implement it properly a bit later. (@glovaeugene)
- [x] "Create password" placeholder → "Password". Basic rule here: this is label which works as placeholder. (@glovaeugene)
