### ISSUE TITLE
Apple pay guidelines and todos

### ISSUE THREAD

**Issue by kairome** [FoxComm/highlander#1551]
## Guidelines:

- Apple pay button is in `Cart`
- No apple pay button on PDP pages or on `Checkout` page
- Only auto promotions will be applied to apple pay customers (no GC/coupon entry)
- The apple pay button should be a one-stop shop, you click it once, fill in the info, make the purchase 
- We don't wanna mix 1-click checkout and Apple Pay checkout

## ToDos:

- [x] Set up a remote testing environment, Sierra MacOS machine (blocking, ASAP) @jmataya 
- [x] Add an endpoint for retrieving shipping methods by a zip code and/or a country code(#1552) @aafa
- [x] Add a state code like `CA` for `California` for every state (#1495) or make an endpoint for getting a `regionId` by looking at the state code @aafa
- [ ] Move the button to `Cart` @Black-Phoenix 
- [ ] Display the shipping methods retrieved from the server @Black-Phoenix 
- [ ] Apply auto promotions  @Black-Phoenix
