### ISSUE TITLE
Product Recommender

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#1666]
# Introduction 
The Product Recommender epic is the implementation of deliverable improvements to the existing recommendation algorithms and services currently prototyped in our system. Our primary goal will be to deliver capabilities that will enable 3rd party integration and a fully functional API that can be consumed by clients.

## Components
As stated in the introduction, the Product Recommender is tasked into deliverable components that although separate will allow us to streamline our workflow and eventually produce a single unified integration point.

### API(Internal)
The API component will require both documentation of endpoints and expected payloads as well as new code.

- [ ] REST endpoints for getting product information by customer, productID
- [ ] REST endpoints to enable tracking. We will probably want to track things such as product views, purchases, add to cart... and more
- [ ] Security either via Header or signed API-Key
- [ ] Publishable API Documentation, similiar to http://api.foxcommerce.com or http://foxcomm.github.io/api-js
- [ ] Cross-Sell javascript logic needs to be brought outside of the storefront modules to make it more 'standalone'
- [ ] Service that allows a delivery of Cross-Sells recommendations via email that link to PDP
- [ ] API Versioning for the Product Recommender

### Client-Side UI(3rd Party)
The Client-Side UI component is envisioned to be a Javascript library that when provided an API-Key a company can use as a widget on their website.

- [ ] Ability to inject a javascript `<script>...</script>` tag onto a clients page, give it an api-key and enable access to our Reccomender API
- [ ] CORS stability, we need to know how each of the major browsers handle making secure requests across Domains
- [ ] Handle sub-domains via Same Origin Policy, SOP
- [ ] Themes and or CSS styling, how can we make our product recommendation widgets match customer's existing styles.
- [ ] Product Ratings
- [ ] Product Reviews

### Client-Side Catalog/Product Import(3rd Party)
The Client-Side Data component is concerned with answering two questions...

1) 'How do we import a customer's catalog data?'

2) 'Where do we store said customer's catalog data?'

- [ ] Investigate Google Analytics for the ability to possibly 'Ingest' a customer's data feed into our systems
- [ ] Build a service that consumes structured product catalog data files which they will upload; CSV, JSON, XML

### Server-Side(Internal)
Internally we will need to both improve our existing algorithms such as those already present in Anthill and create new ones to handle the demands of our customers. In addition some kind of configuration and access-privileges system needs to be created or integrated into one of our services.

- [ ] Purchase History Algorithm, determine upsell from previously purhcased products
- [ ] Conversion Tracking, How often does Product Viewed --> Product Purchase
- [ ] Item-Item Collaborative Filtering, Recommend based on a user's rating of a product
- [ ] Inventory Awareness, For example, don't recommend products that are out of stock
- [ ] Previously Suggested, Split between 'By-Again?' versus 'Has already been suggested in the past X days'
- [ ] Clustering and Demographics, For example top 10 Products for 18-35 year old women who previously bought item Foobar
- [ ] Configuration and turn-key deployment, Can we allow customers to enable/disable specific recommendation features?
- [ ] Customer Authorization, don't allow customers to see other companies data
- [ ] Customer Authentication, API-Keys
- [ ] Product Ratings
- [ ] Product Reviews

### Server-Side(3rd Party)
Depending on the customer we building out a product for we might need to create custom integrations for existing E-commerce platforms.

- [ ] Magento categories and products to taxonomy
- [ ] Official FoxCommerce Magento plugin

## Timeline
Subject to change based on prioritization.

### Sprint 5-4-2017 _Week 1_ Deliverables 

- Start work on Cross-Sells standalone widget
- Product Reviews

---

### Sprint 5-18-2017 _Week 2_ Deliverables

- Cross-Sells standalone widget
- Cross-Sell Recommendation via Email
- Google Analytics Investigation + Outline of GA strategy
- 3rd party catalog/product Import to FoxCommerce Taxonomy upload
- Product Ratings
