### ISSUE TITLE
Cross-Sells Standalone Widget

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#1708]
## Description
The goal is to extract the current cross-sell widget's functionality from being coupled to the existing storefronts where the code has been deployed. This will result in a modular cross-sell widget that can be dropped in place onto any given storefront with minimal configuration

### Tasks
- [ ] Move existing cross-sell logic from outside of the storefront and place it elsewhere
- [ ] Figure out a way to isolate as much of the CSS styling as possible
- [ ] Ensure that any requests the cross-sells widget makes are secure
- [ ] Enable cross-sell widget to embedded onto a web page

### Customization
- [ ] Styles and features should be added in Ashes, CSS file upload

### Deployment
- [ ] We need a strategy to work with possibly duplicate libraries such as React when we add the script.
