### ISSUE TITLE
Product Ratings System

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#1709]
## Description
Up until now there hasn't been a way for customers to rate how well they enjoyed or disliked they have purchased. The goal of this task is to enable a way for customers to "rate" products.

## Tasks UI
- [ ] Decide on a visual indication of "like" or "dislike", this can be a 5 star rating or simple "Yes or No"
- [ ] Display the rating value somewhere on an existing PDP page
- [ ] Modify an existing orders page or create a new form where customers who have purchased products can go back and "rate" them.

### Tasks Backend
- [ ] Design a product ratings persistence strategy
- [ ] API endpoint to enable customers to apply a rating to a product
- [ ] API endpoint to enable fetching product ratings
- [ ] PostgreSQL  new Tables for Ratings
