### ISSUE TITLE
Product Reviews System

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#1710]
## Description
Up until now there hasn't been a way for customers to leave reviews on products they have recently purchased. The review system should at a minimum allow for customers to write some text about their recent purchase. If possible we could allow uploading images or enable social media sharing.

## Tasks UI
- [x] Decide how the reviews should be displayed on the PDP page
- [x] Modify an existing orders page or create a new form where customers who have purchased products can go back and write a "review" about them.
- [x] Ensure that reviews can be "paginated" so we don't clutter the PDP
- [x] Enable a "flag review as inappropriate"

### Tasks Backend
- [x] Design a product reviews persistence strategy
- [x] API endpoint to enable customers to apply a review to a product
- [x] API endpoint to enable fetching product reviews(should support pagination)
- [ ] Keep track of the total number of "flagged as inappropriate", so we can choose to filter out nasty reviews or obvious trolling.
- [x] PostgreSQL  new Tables for Reviews

UI Research
---

- Amazon review with product variant

![amazonreview](https://cloud.githubusercontent.com/assets/833843/25761786/e3c0db66-3190-11e7-82c4-47e987b3aee6.png)

- Nike review with simple widgets and product review sliders

![nikereview](https://cloud.githubusercontent.com/assets/833843/25761977/b2552568-3191-11e7-847f-7b8131e9753f.png)

UI Mocks Version 1
---
- PDP With Reviews
![pdp_with_reviews_v1](https://cloud.githubusercontent.com/assets/833843/25929089/e26d56f4-35b4-11e7-8b78-14e3572e4901.png)

- My Account Page With Empty Reviews
![empty_reviews_v1](https://cloud.githubusercontent.com/assets/833843/25929102/fdd04dde-35b4-11e7-8247-051787b82783.png)

- My Account Page With Populated Reviews
![populated_reviews_v1](https://cloud.githubusercontent.com/assets/833843/25929111/0a3b2440-35b5-11e7-9196-edf88695eef7.png)

- Add/Edit Review Screen
![updatereviewnomodal](https://cloud.githubusercontent.com/assets/833843/26076414/840c9e78-396d-11e7-89f9-5ca8cbaed579.png)
