### ISSUE TITLE
Updates for Product Reviews

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#1829]
## Description
The current JSON serialization of a Product Review object when returned from the Elastic Search topic `product_reviews_search_view` is the following

```
"result": [
    {
      "sku": "S75187_640",
      "id": 2,
      "scope": "1.2",
      "title": "sweet shoes (updated AGAIN after some use)",
      "createdAt": "2017-05-16T21:32:37.790Z",
      "updatedAt": "2017-05-16T21:32:37.790Z",
      "body": "This is an updated review.",
      "archivedAt": null,
      "userName": "test test"
    },
    ...
]
```
In order to move forward with Product Reviews we will need some minor adjustments.

### Tasks
- [x] Include a customerID or a way to identify the customer who created the review
- [x] If possible can we include the Order Reference Number

### Bugs
- [x] `updatedAt` and `createdAt` are always the same, even after a `PATCH` request is made to update the Review. CreatedAt should never be modified.

### New Feature, Product Review "Status"
Every Product Review should have an enumeration type which consists of the following.

```
product.review.status == { 'pending' | 'ignored' | 'submitted' }
```
- Pending
The initial and default status.
When a an item is ordered by a customer, we should create a `pending` product review for every item.

- Ignored
On our UI, the customer has the option to say "No Thanks" or "Ignore" this product review.

- Submitted
After a customer has filled out the web UI form for a `pending` review it should update the title, body, updatedAt and change the status from `pending` => `submitted`
