### ISSUE TITLE
MWH kangaroos backport

### ISSUE THREAD

**Issue by annappropriate** [FoxComm/highlander#1858]
Task: backport MWH changes @jmataya introduced in kangaroos branch to master
Long-term goal: synchronous communication between phoenix and MWH, stock items consumer gone
# Round 1:
Leave phoenix as-is, make consumer propagate changes to SKUs instead of stock item.
Description from @jmataya 
![phoenix-to-mwh](https://cloud.githubusercontent.com/assets/1017417/26299143/700460d0-3ee2-11e7-9c0c-f7f83dc8aa39.png)

> Kangaroos gets rid of this long term, in favor of a synchronous connection between Phoenix and MWH, but we can use it to our advantage now
> Today, `stock item consumer` listens for creations and updates to `sku` and propogates those changes to `stock items`
> Modify it do propogate changes to MWH `sku` instead
> And leave phoenix as-is
> Once new code it deployed, simply touch all of the SKUs (via the API) in Phoenix to have the consumer pick them and migrate to MWH

## Roadmap
@lurym please attach PRs to track the progress
- [x] technical changes: transactions and stuff
- [x] create SKU model and endpoints
- [x] come up with solution to touch all SKUs via API and how to run it on environments
- [x] change consumer to propagate changes to SKU instead of stock item
- [ ] run migration script on prod copy and later prod env #2057 

# Round 2:
*we need more discussion on this*
- Assume SKUs are migrated from phoenix
- We want SKU code to be mutable
- Probably must happen after moving phoenix from using SKU code to SKU id internally

# Roadmap
- [ ] Update stock item consumer and middlewarehouse on production environment
- [ ] Run migrate_sku script as in #2057
- [ ] Verify and merge pull request #1910 (these are Jeff's changes from kangaroos branch)
- [ ] Verify and merge pull request #2238 (updated error message when client orders more items than in stock)
- [ ] Verify and run migrate [script](https://github.com/FoxComm/highlander/blob/c962fe64a8f31f99c1dd2ef4ddf65c7c8947e1bc/skusquery.sql) which moves sku_id from MWH to Phoenix

## Roadmap (old and no longer actual)
- [x] in phoenix, introduce mapping between phoenix and MWH SKU ids
- [ ] SKU id migration SQL between phoenix and MWH
- [x] make phoenix create MWH SKU synchronously as part of SKU creation https://github.com/FoxComm/highlander/pull/2105
- [x] get rid of stock item consumer https://github.com/FoxComm/highlander/pull/2105
