### ISSUE TITLE
Try Nixy instead of Consul Template + Marathon Consul

### ISSUE THREAD

**Issue by pavel-main** [FoxComm/highlander#1881]
Epic #1112 

## Description

> Unfortunately, only commercial version of Nginx can [load upstreams dynamically from Consul](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#service), we're using [consul-template](https://github.com/hashicorp/consul-template) as a workaround for that (two instances!), but there is no way to trigger it's reload from Nginx itself, which leads to minor downtime and 502 errors. [Nixy](https://github.com/martensson/nixy) is doing the same thing as Consul Template, except, it is continuously reading Marathon applications via it's Event Bus, without man-in-the-middle apps like [marathon-consul](https://github.com/allegro/marathon-consul).

## TODO

- [x] Launch an appliance, disable `consul_template`, `demo_consul_template` and `marathon_consul` services.
- [x] Install and configure Nixy, test it by restarting / suspending Marathon applications.
- [x] Modify provisioning scripts to replace 3 services with one.
