### ISSUE TITLE
Finish Multi Tenancy

### ISSUE THREAD

**Issue by mempko** [FoxComm/highlander#1998]
# Goal

Support merchants having multiple storefronts for different global regions.

TODO: Insert link to design doc.
TODO: Insert links to any use cases.

# Do
- Do test from frontend and api level.
- Do test on the new stage environment.
- Do develop incrementally. Usable software at each increment.
- Do develop small software that does one thing well.

# Dont
- Don't unit test.
- Don't refactor unless you add functionality or performance improvements.
- Refactor existing work unless it adds functionality or performance improvements.

# High Level Work
The following items need to be blown out.

- [ ] Add new models. Use solomon to manage them?
- [ ] Scope remaining data models. See below.
- [x] Settings model and plugins need to be scoped. 
- [ ] Consumers using plugins API should take scope into account for each activity when getting plugin settings.
- [ ] Determine how channel is selected for public apis. We have river-rock->headers started. 
- [ ] Make customer registration channel aware instead of using config inside phoenix.
- [ ] Make public product catalog search channel aware. Index per channel.
- [ ] Make public product/sku endpoints channel aware.
- [ ] Make public taxonomy APIs channel  aware.
- [ ] Ability to manage catalogs in ashes.
- [ ] Ability to manage storefronts in ashes. (at this point views should be implicitly managed)
- [ ] Ability to create new sub organization which branch from current orgs catalog/merch data.

# Known Issues that need fixing.
- [ ] Creating a new organization in solomon onboarding doesn't create a stock item location in middlewarehouse. 
- [ ] stock-item-consumer should lookup stock item location based on scope and assign that to stock in middlewarehouse.
- [ ] Settings API

# Data models that need to be scoped.

## phoenix
- [x] plugins
- [ ] returns
- [ ] returns_search_view
- [ ] shipping_methods
- [ ] object_contexts
- [ ] object_schemas
- [ ] gift_cards
- [ ] gift_cards_search_view
- [ ] order_criteria
- [ ] order_destination_criteria
- [ ] order_dimension_criteria
- [ ] order_price_criteria
- [ ] order_weight_criteria
- [ ] customer group templates (needs verification)
- [ ] failed_authorizations_search_view

## hyperon

- [ ] amazon_submission_results
