### ISSUE TITLE
Marathon Groups: Next Level

### ISSUE THREAD

**Issue by pavel-main** [FoxComm/highlander#2033]
## TODO

- [x] Add optional `onboarding` backend and UI to Highlander group (#2038)
- [x] Atomic deployments, instead of killing whole group & re-deploying (#2062)
- [x] Modify `projects.sh` to catch up **every** project update (#2081)
- [x] Add optional `shipstation` integration (#2091)
