### ISSUE TITLE
CMS - Ashes Content Types

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#2070]
## Description

The first iteration of FoxCommerce's CMS will provide the ability for customers to inject dynamic content onto their storefronts via the Ashes Admin panel.

![screen shot 2017-06-06 at 10 44 13 am](https://user-images.githubusercontent.com/833843/26843567-8d20e552-4aa5-11e7-8afa-cef0cfcf4400.png)

## FrontEnd Tasks

- [x] New `Content` Sub section on Ashes sidebar - https://github.com/FoxComm/highlander/issues/2093
- [x] `Content Types` Main sub-page that _Lists_ all existing types by `Name, Slug, Description, Date/Time Created, Date/Time Last Modified` - https://github.com/FoxComm/highlander/issues/2093
- [ ] New Content Type Creation Page top most part `General` with `Title, description, slug` - https://github.com/FoxComm/highlander/issues/2094
- [ ] New Content Type Creation Page bottom most part `Tab, Section, Properties, Property Setting` - https://github.com/FoxComm/highlander/issues/2096
- [ ] Component that can render a Content Type editable properties and sections page from a serialized JSON response - https://github.com/FoxComm/highlander/issues/2100

## BackEnd Tasks

**Elixir CMS Backend Geronimo**
https://github.com/FoxComm/protos/tree/master/geronimo

- [ ] Content Type API for `CREATE, PUT, POST, DELETE`

## Invision Prototype Link
https://invis.io/VNBNUNUGR#/233161134_Content_Types

## Content Types

Content types are aggregate combinations of "Properties".

### Example: "Testimonial" Content Type

- A customer wants to add "testimonials" to their site
- They begin by defining the meta-data for a a new "Content Type"
- Currently the meta-data consists of a Title, Description and Slug

![screen shot 2017-06-06 at 10 51 43 am](https://user-images.githubusercontent.com/833843/26843767-35f858b8-4aa6-11e7-96a4-f91890b19ee2.png)

- Next customers can add "Tabs", "Sections", "Properties" and "Property Settings"

![screen shot 2017-06-06 at 11 03 33 am](https://user-images.githubusercontent.com/833843/26844330-e48b6ca2-4aa7-11e7-9f4e-027eb2f7b6d9.png)

### Section

- Sections are "Property" groups, which are nested under a "Tab"

![screen shot 2017-06-06 at 11 05 15 am](https://user-images.githubusercontent.com/833843/26844371-122ba974-4aa8-11e7-8d7f-74457cdf4cd6.png)

### Properties and Property Settings

- After a section is created the properties are added. In the example we add three properties to our section; "Author - Text", "Content - Text Area", "Lorem Ipsum Image - Image" and "Dolor Sit Amet - Text"

- Property = Property Name + Property Type
- Property Type = Label + Field + Slug

![screen shot 2017-06-06 at 11 09 19 am](https://user-images.githubusercontent.com/833843/26844625-eb9eca42-4aa8-11e7-803e-3a2b4fe41986.png)

### _When a user has defined a Tab which holds a Section which is composed of its Properties_ the visual display will be rendered as the following

![screen shot 2017-06-06 at 11 13 51 am](https://user-images.githubusercontent.com/833843/26844804-7d4bd926-4aa9-11e7-8019-2e2c7dd879f4.png)

## Overview

- Each content type is a nested structure of its components; Tab, Section, Properties and Property Settings

![contenttype](https://user-images.githubusercontent.com/833843/26845758-612c8dd2-4aac-11e7-8c59-067831342a5f.png)

## JSON structure

Work in progress... will add it here when done
