### ISSUE TITLE
New promotions module

### ISSUE THREAD

**Issue by annappropriate** [FoxComm/highlander#2127]
# New promotions module

Link to documentation: https://github.com/FoxComm/highlander/tree/master/documents/design/promotions

Why do we want to go for new implementation instead of refactoring old one:
1. existing code is heavily tied to other parts of phoenix. Moving is total pain
1. implementation must be changed anyway
  - promotions must be implemented on relational model rather than form/shadow
  - ES queries are difficult to track and often superfluous

## Approach
1. start not from model definitions, but from an API. For now, promotions will exist as phoenix module, so API is purely programmatic rather than HTTP, but this approach should be taken in case of HTTP API implementation as well.
1. promotions module should know nothing about other entities existing in phoenix. It must receive some primitive data and either use it in qualifiers or echo back for API convenience.
1. module should not make any external calls to ES or Kafka or whatever
1. tests should be contained in promotions module and broken down into multiple test suites instead of one multiple hundred lines integration test.

## Migration to new module
What I'm thinking about is:
1. As soon as module API is ready (even as a stub), start placing calls to new module in phoenix code where they're supposed to be
1. When module impl is ready, migrate old data to new tables
1. Leave both implementations (old and new) running in phoenix only on dev/stage envs
1. Compare results in search views, switch dev/stage to new version of search view
1. If new module behaves well, rip out old impl

## Open questions
- ExecutionContext — one per module?
- Database — separate schema?
- Clean up method signatures from all the implicits?

## General technical design changes
- DAOs: instead of putting individual queries on table companion objects, have a proper DAO layer with joining queries
- Tests: instead of having one gigantic test, break them down into smaller suits
- Failures: this is a good chance to try and define a new Failure structure
- Use `NonEmptyList` where appropriate
- Use `List` instead of `Seq`

### Phase 1: Pre
- [ ] Figure our requirements
- [ ] Investigate corner cases
- [ ] Tech spec for data models

Start with basic outline, define streams of parallel work.
It's totally possible for us to start writing tests before the implementation is done as we already have a set of existing ITs that we can analyze and migrate.

Create in code:
- [ ] Compilable phoenix module
- [ ] `PromotionsAPI` object with stubbed methods
- [ ] `CouponsAPI` object with stubbed methods

The above objects are two only entry points for phoenix. `API`s should each have a sufficient API defined for a full-blown communication. We need to define how we _want_ them to look.
I would also argue that `PromotionsBulkAPI` and `CouponsBulkAPI` must be separate objects.

- [ ] Test suite definitions — as a prerequisite, test framework must be moved into separate module. If tech spec is not ready at this point, we can still start migrating existing tests and translating use cases into new tests.

For test suites, I would like a better separation: I think each method in API object deserves its own suite at very least

- [ ] Setup to put module tables in new database schema — might require some database def changes

### Phase 2: Barebone promo implementation
Everything should be ready at this point for implementation to be filled in.   
Requires tech spec.
- [ ] Tests for CRUD
- [ ] Models
- [ ] DAOs
- [ ] CRUD

### Phase 3: Auto-apply algorithm
Auto-apply seems more difficult to get right than coupons, so I suggest we start with it.
- [ ] Tests for auto-apply promo selection
- [ ] Algorithm design
- [ ] Investigate caching or other optimizations
- [ ] Implementation
- [ ] Performance tests for auto-apply?

### Phase 4: Coupons implementation
- [ ] Tests for CRUD
- [ ] Models
- [ ] DAOs
- [ ] CRUD

### Phase 5: Auto-apply vs coupons
I figured this deserves a separate section. If, by any chance, we already have this covered, then this can be skipped. Otherwise, spend some time on this.
- [ ] Dive deeper into interplay
- [ ] More edge case tests

### Phase 6: Search view
Instead of building a trigger-based table in postgres, push directly to Kafka
- [ ] Spike/investigation
- [ ] Investigate transactionality — make sure we push only if transaction isn't rolled back
(hence, module does not push to kafka directly, phoenix does that)
- [ ] Implementation
- [ ] BVT (?) tests for search view

### Phase 6: Versioning
To implement relational versioning, consider using this trigger approach that Roman uses for CMS.
This section will be filled in later.
