### ISSUE TITLE
Add Geronimo To Tabernacle

### ISSUE THREAD

**Issue by taywils** [FoxComm/highlander#2166]
## Description 
We will need to add the Geronimo CMS backend project to our appliance build. Specifically in Tabernacle we will need to add some yaml config files and update the Nginx to include Geronimo.

https://github.com/FoxComm/highlander/issues/2070

## Tasks
- [x] Add Ansible Dev Roles Marathon task for Geronimo, `app_geronimo.yml`
- [ ] Include Geronimo in the new `builder.py` file in Highlander
- [x] Create a  flyway conf file in the Directory `tabernacle/ansible/roles/dev/db`
- [x] Update `tabernacle/ansible/roles/dev/marathon/tasks/backend/.yml` file with the reference to `app_geronimo.yml`
- [x] Update the Balancer Template `tabernacle/ansible/roles/dev/balancer/templates/service_locations.j2`. We should base the Geronimo service location on an existing one such as `middlewarehouse`

## Seed Data For Geronimo
- [ ] We will need a way to generate some sample data for Geronimo that will populate the content_types and entities tables in PostgreSQL. This can either be an additional `sql` script in Geronimo or something else that hits the API or possibly a script written in Elixir. 

```
geronimo_development=# \dt
                 List of relations
 Schema |         Name          | Type  |  Owner   
--------+-----------------------+-------+----------
 public | content_types         | table | geronimo
 public | content_types_history | table | geronimo
 public | entities              | table | geronimo
 public | entities_history      | table | geronimo
 public | schema_version        | table | geronimo
(5 rows)
```

Current Geronimo REST API https://github.com/FoxComm/protos/tree/master/geronimo
