### ISSUE TITLE
Apply styles to the Styleguide

### ISSUE THREAD

**Issue by tonypizzicato** [FoxComm/highlander#2193]
Mockup https://zpl.io/ZUOSa

> Content:
> 1. Let's leave Raleway for h2/h3, and use OpenSans for everything else (except code)
> 2. Props & methods, and code dropdowns are not looking as clickable components, so added arrow near them.
> 3. Changing code updates displayed components. So maybe we should integrate 'Show code' inside upper container and merge their containers (see on the mockup, bottom) to show they are related?
> 4. We should probably not display edge cases of components usage. It makes these containers messy. I know you need to be sure these cases are working properly but what if we create separate page for that?

> Sidebar navigation:
> 1. Let's get rid of 4th level and stick with 3 levels nesting. We can do it if replace Components → Core & Utils with Core components & Util components. You can suggest what more suits you :slightly_smiling_face:
> 2. What would be cool is to have ability to highlight current position on the page. 
> 3. What would be even more cool is to have ability to collapse all 3rd level navigation except current.

#### Todo
- [x] Update fonts
- [x] Update sidebar styles
- [ ] Fix page title (remove `Version <span....`)
- [x] Update components styles
- [x] Cleanup sections (reduce to 3 levels max)
- [x] Sidebar items collapsing and highlighting

#### Optional
- [ ] One component per page
