### ISSUE TITLE
Remaining inputs refactoring

### ISSUE THREAD

**Issue by tonypizzicato** [FoxComm/highlander#2194]
Refactor/cleanup remaining input components

#### TODO:
- [ ] PilledInput
- [ ] PlatedInput
- [ ] PrependInput 
- [ ] AppendInput
- [ ] CurrencyInput
- [ ] Prepend/Append icon inputs are still in file system but they are empty
- [ ] LoadingInputWrapper is just a `div` that wraps spinner and any children passed to it. Maybe it can be reworked somehow to be responsible for managing input component itself instead accepting children
- [ ] LookupInput does nothing except adding `fc-lookup` className and used just in `Lookup` component, so can be deleted
- [ ] MaskedInput (used only in live-search, but commented right now (was used for dates input), so, we need to decide if we need it at all)
- [ ] PasswordInput

#### UPD
Maybe it makes sense to move them all to one `core/input` directory
