### ISSUE TITLE
Dropdowns refactoring

### ISSUE THREAD

**Issue by tonypizzicato** [FoxComm/highlander#2196]
#### TODO:
- [ ] move dropdowns to core, css-modules, tests
- [ ] refactor/cleanup dropdowns
- [ ] add keyboard support
- [ ] cleanup/improve hierarchical dropdowns

https://zpl.io/P83Si
https://zpl.io/Z39JBU
